apiVersion: v1
kind: Namespace
metadata:
  name: notes-pwa
  annotations:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-pwa-app
  namespace: notes-pwa
  labels:
    app: notes-pwa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-pwa-app
  template:
    metadata:
      labels:
        app: notes-pwa-app
    spec:
      containers:
        - name: notes-pwa-app
          image: docker.io/gunter04/pwa-exapp01:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notes-pwa-service
  namespace: notes-pwa
spec:
  selector:
    app: notes-pwa-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: ClusterIP
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: notes-pwa-apirule
  namespace: notes-pwa
spec:
  gateway: kyma-system/kyma-gateway
  host: godrej-pwa
  rules:
    - accessStrategies:
        - handler: no_auth
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
        - OPTIONS
      path: /.*
      service:
        name: notes-pwa-service
        port: 8080
      timeout: 60
  service:
    name: notes-pwa-service
    port: 8080


